project:
  type: book
  output-dir: output
format:
  pdf:
    papersize: a4
    documentclass: scrreprt
    toc: true
    lof: true
    lot: true
    include-in-header: 
      text:
        \usepackage{imakeidx, bibentry, multicol}
  html: default

number-sections: true

mainfont: "Times New Roman"
sansfont: "Arial"
monofont: "Courier New"
mathfont: "TeX Gyre Termes Math"

book:
  title: "Aligning business processes with regulatory requirements"
  subtitle: "a systematic literature review"
  downloads: [pdf,docx]
  search: true
  repo-url: https://github.com/jan-ru/phd_kul
  author: 
    - name: "Jan-Ru Muller"
      orcid: 0000-0003-1689-0557
      email: janru.muller@edu.vlerick.com
      affiliations:
      - name: Amsterdam University of Applied Sciences
        address: Fraijlemaborg 133
        city: Amsterdam
        country: The Netherlands
        postal-code: 1102 CV
      - name: Vlerick Business School
        address: Reep 1
        city: Ghent
        country: Belgium
        postal-code: 9000
  date: "4/26/2024"
  date-format: "DD/MM/YYYY"

  chapters:
    - index.qmd

  appendices:
    - s2_slr_doc_a_databases_searched.qmd

license: "CC BY"
latex-output-dir: output

bibliography: MyLibrary.bib
#  main: MyLibrary.bib
#  software: MySoftware.bib

#citeproc: false

#filters:
#  - multibib
#validate-yaml: false
