project:
  type: book
  output-dir: output

metadata-files: 
  - ./metadata/_format.yml
  - ./metadata/_website.yml

number-sections: true

mainfont: "Times New Roman"
sansfont: "Arial"
monofont: "Courier New"
mathfont: "TeX Gyre Termes Math"

book:
  title: "Pilot"
  subtitle: "a pilot study"
  downloads: [pdf,docx]
  search: true
  repo-url: https://github.com/jan-ru/yr2_pilot
  author: 
    - name: "Jan-Ru Muller"
      orcid: 0000-0003-1689-0557
      email: janru.muller@edu.vlerick.com
      affiliations:
      - name: Amsterdam University of Applied Sciences
        address: Fraijlemaborg 133
        city: Amsterdam
        country: The Netherlands
        postal-code: 1102 CV
      - name: Vlerick Business School
        address: Reep 1
        city: Ghent
        country: Belgium
        postal-code: 9000
  date: "5/11/2024"
  date-format: "DD/MM/YYYY"

  chapters:
    - index.qmd
    - s3_case.qmd

  appendices:
    - s3_case_prior.qmd

license: "CC BY"
latex-output-dir: output

bibliography: MyLibrary.bib
#  main: MyLibrary.bib
#  software: MySoftware.bib

#citeproc: false

#filters:
#  - multibib
#validate-yaml: false
