---
title: "Untitled"
format: html
---

### Follow-up

Contact persoon xbrl amsterdam (dienstverlener woningbouwcorporaties)

Overview of alternatives for Alliander (sector code)

Voorbeeld PhD Eindhoven (KUL) [Irene Vanderfeesten](https://www.linkedin.com/in/irene-vanderfeesten-a712355/)  ORCID toevoegen.

To watch: [arcrole](https://www.arcrole.com/) in Vlaardingen

Thauris Sebastiaan Bol

Overview of housing cooperations in the Netherlands (sector code)
aedes

GRC was first defined by Scott Mitchell, OCEG, in 2007 as:

the integrated collection of capabilities that enable an organization to reliably achieve objectives, address uncertainty and act with integrity.²

[NL Overheid](https://gist.github.com/JulesBlm/828ee88c018bf528d3cd513d060fe1fb)
Misschien moet de index.html op een server staan?
Zie Github JulesBlm ofwel Jules Blom (front-end developer)

Paragraph about participation in the ESEF seminar organised by XBRL NL op 9 Nov 2023.

Paragraph about participation in the Vlerick Digital Finance Conference 2022 at BluePoint Antwerpen (May 2024).

Paragraaf over overleg met oprichter Caseware.

----

The role of technology in integrated, sustainable reporting.

Discover the role of technology in integrated, sustainable reporting during the Digital Finance Conference 2022 on May 24 organized by the Vlerick Business School and the Centre for Financial Leadership & Digital Transformation. 

Get inspired by Prof Dr Robert Kaplan of Harvard Business School and other industry peers and grab the opportunity to share insights with fellow delegates during three unique tracks and a round table discussion with both national and international CFOs: 
 
Track 1 | Sustainability reporting and standards:
Evolution of current sustainability standards and reporting requirements

Track 2 | Sustainability and technology:
Use of technologies to collect and analyse data for more sustainable reporting

Track 3 | Sustainability and reward:
Remuneration from both an academic and a market perspective

Jean-Paul Servais, chairman of the FSMA gave a speech on The Belgian and international perspective on ESG disclosures at the Digital Finance Conference in Antwerp.

Integrated reporting in practice: the past and the future
Ilse Lampaert (Group Finance Head Policy Advice Sustainability Disclosures, KBC) 

Snippets:  

Sample table control objectives and controls (from ISO 27001):  
A18 Compliance  
A18.1 Compliance with legal and contractual requirements  
Objective: To avoid breaches of legal, statutory, regulatory or contractual obligations related to information security and of any security requirements.  
A18.1.1 
Description: Identification of applicable legislation and contractual requirements  
Control: All relevant legislative statutory, regulatory, contractual requirements and the organization's approach to meet these requirements shall be explicitely identified, documented and kept up to date for each information system and organization.

Author contributions  
Conceptualization, S.A. and A.V.L.; methodology, A.V.L. and S.A.; writing—original draft preparation, S.A.; writing—review and editing, A.V.L. and G.P.; supervision, A.V.L. and G.P. The authors have read and agreed to the published version of the manuscript.
