---
project:
  type: default
  output-dir: output
title: ""
subtitle: "Agile Law Making (Thesis)"
date: "11-01-2023"
date-format: "D/MM/YYYY"
date-modified: "10-23-2023"
author:
  - name:
    orcid: 0000-0003-1689-0557
    email: j.r.muller@hva.nl
    affiliations:
      - name: Amsterdam University of Applied Sciences
        address: Fraijlemaborg 133
        city: Amsterdam
        postal-code: 1102 CV
      - name: Vlerick Business School
        address: Reep 1
        city: Ghent
        postal-code: 9000
abstract: ""
format:
  pdf:
    cite-method: citeproc
    include-in-header: 
      text:
        \usepackage{imakeidx, bibentry}
latex-output-dir: "output"
toc: false
toc-depth: 2
bibliography: MyLibrary.bib
keywords: modelling languages, controlled natural language

---
If part of a book project:  
Three types of variable: var, meta, env.

var: {{< var email.info >}}  
meta: {{< meta subtitle >}}  
env: {{< env AWS_ACCESS_KEY_ID >}}  

# Mariette Lokin

## Thesis

The thesis by Mariette Lokin was published in 2018 (in Dutch) by the Vrije Universiteit Amsterdam (@lokinWendbaarWetgevenWetgever2018). It is available at the [research portal](https://research.vu.nl/en/publications/wendbaar-wetgeven). Mariette work is the inspiration for my thesis where I want to use the lens of a multinational enterprise. On 17-11-1021 I emailed Mariette and we spoke via Teams on 17-12-2021. 

## Research question

RQ: To what extent and in what way can digital execution of legislation by national government agencies be taken into account in the legislative process?

Five supporting research questions are listed in the attachment.

## Theories/concepts mentioned in the intro

Paragraph 1.5 describes legislation as a product. Specifically it describes how technologies like language models, linked data and a formalized legal domain vocabulary can ease the translation of regulatory texts into computer programs. The identification of these three tools there are three research questions formulated (appendix, question 1,2,3)

Paragraph 1.6 describes the law making process. Specifically the question if in the law making process there is sufficient consideration for the influence of technological developments on the execution of legislation. From this observation two additions research questions are formulated (appendix, questions 4 and 5).

## Brief description of the research method

Five cases are described at two government agencies. Additionally, one cross-domain application is described.:

| #     | Subject                     | Ministry                |Chapter|
|-------|-----------------------------|-------------------------|-------|
|case 1 | Tax Office                  | Ministry of Finance     | 2.4.2 |
|case 2 | Tax Office                  | Ministry of Finance     | 2.4.2 |
|case 3 | IND                         | Ministry of Justice     | 2.4.3 | 
|case 4 | IND                         | Ministry of Justice     | 2.4.3 |
|case 5 | Standard Business Reporting | cross-domain application| 2.4.4 |

## Conclusion

The conclusion is that there are realistic possibilities for lawmakers to take into account the digital execution by designated executive government agencies. 

- A language model aids with precise formulation and creation of specifications for digital execution.

- A legal vocabulary (CNL) provides for insight into the diversity of terminology and allows for analysis to reduce diversity.

- The application of linked data provides for insight into the 'web' of laws and related documents for insight into applicable rules and meaning.

## Suggestions for further research

The future perspective is that the legal technical information on wetten.nl no longer only contains references to other regulations and case law, but also to decision rules based on the relevant article. The future perspective is that the legal technical information on "wetten.nl" no longer only contains references to other regulations and case law, but also to decision rules based on the relevant article. "In my opinion, a role for the legislator in advance in guaranteeing legal protection in automated decision-making through transparency and traceability of decision rules and algorithms is more obvious than setting up retrospective control."

\newpage

## Translated Research Questions[^1]

RQ1 : Can a language model be created based on analysis of the structure and formulation of legislation with which legal concepts in legislation can be made unambiguously recognizable?

RQ2 : Can a useful legislative vocabulary be generated from manifestations of legal concepts based on annotation of legislation using the language model?

RQ3 : Can the use of linked data in the drafting of legislation improve insight into the legal rules relevant to the digital implementation of a specific task and insight into explanatory notes and parliamentary history?

RQ4 : What support is needed in the legal legislative process to implement the language model, to apply a legislative vocabulary and linked data?

RQ5 : What changes are necessary in the administrative-political legislative process to realize multidisciplinary cooperation in the phase of official preparation of legislation, and to give technological rationality its own place in the phase of parliamentary consideration of legislation?

[^1]: Translated from Dutch into English with Google Translate.

## Original Research Questions

OV : In hoeverre en op welke wijze kan bij het tot stand brengen van wetgeving rekening worden gehouden met digitale uitvoering door uitvoeringsorganisaties van de rijksoverheid?

OV1 : Kan op basis van analyse van de structuur en formulering van wetgeving een taalmodel worden gecreëerd waarmee juridische concepten in wetgeving eenduidig herkenbaar gemaakt kunnen worden?

OV2 : Kan op basis van annotatie van wetgeving aan de hand van het taalmodel een bruikbaar wetgevingsvocabulaire worden gegenereerd van verschijningsvormen van juridische concepten?

OV3 : Kan met toepassing van linked data bij de redactie van wetgeving het inzicht in de voor digitale uitvoering van een bepaalde taak relevante wettelijke regels en het inzicht in toelichtingen en parlementaire geschiedenis worden verbeterd?

OV4 : Welke ondersteuning is nodig in het juridische wetgevingsproces om het taalmodel, het wetgevingsvocabulaire en linked data te kunnen toepassen?

OV5 : Welke veranderingen zijn nodig in het bestuurlijk-politieke wetgevingsproces om een multidisciplinaire samenwerking te realiseren in de fase van ambtelijke voorbereiding van wetgeving, en om de technologische rationaliteit een eigen plaats te geven in de fase van parlementaire behandeling van wetgeving?

## Other publications (co)authored by Mariette Lokin

The first publication of Mariette in my Zotero library is from 2015: @vanhoutumEenKapstokVoor2015. On the subject of the thesis there has also been a publiction in english (@lokinAgileLawMaking2020). The controled natural language (CNL) is called RegelSpraak. Is is described in: @corsiusRegelSpraakCNLExecutable2021, from the same year is: @ausemsWetsanalyseVoorEen2021.


# Ivar Timmer




## References