---
project:
  type: default
  output-dir: output
title: "status update"
subtitle: "Vlerick DBA - Mini Case Study"
date: "02-17-2024"
date-format: "D/MM/YYYY"
date-modified: "02-17-2024"
author:
  - name: Jan-Ru Muller
    orcid: 0000-0003-1689-0557
    email: j.r.muller@hva.nl
    affiliations:
      - name: Amsterdam University of Applied Sciences
        address: Fraijlemaborg 133
        city: Amsterdam
        postal-code: 1102 CV
      - name: Vlerick Business School
        address: Reep 1
        city: Ghent
        postal-code: 9000
co-authors:
  - name: Amy Van Looy
  - name: Stijn Viaene
abstract: ""
format:
  pdf:
    cite-method: citeproc
    include-in-header: 
      text:
        \usepackage{imakeidx, bibentry}
latex-output-dir: "output"
toc: false
toc-depth: 2
bibliography: MyLibrary.bib
keywords: modelling languages, controlled natural language

---
After discussion (online: 28/11/2023) about the Mini Case Study document (appendix) we settled on the following:

- MedTech: not to pursue this prospect as the organization is only in the early stages of applying BPM.
- Financial Institution: maybe of interest as certain parts of the organisation will likely be more advanced in the application of BPM then other parts of the organisation. This may provide for an opportunity to contrast two parts of the organisation.
- Housing Association: maybe of interest as a semi-public organisation. We concluded that semi-government and/or semi-public organisations maybe ahead of private organisations in implementing new regulatory requirements.

### Alliander

When discussing possible candidates where a pilot case study can be performed we discusses it might be useful to focus on semi-public organisations such as utility companies or indeed housing cooperations.

One such utility company is [Alliander](https://www.alliander.com), it develops and operates energy networks. I received from Stijn the contact details of [Pallas Agterberg](https://www.linkedin.com/in/pallas-agterberg-9564a95/) and [Perry Nouwens](https://www.linkedin.com/in/perrynouwens/) at Alliander. I have contacted Pallas[^1]. From my own network I contacted [Tiemen van der Tuin](https://www.linkedin.com/in/tiemen-van-der-tuijn/), who works with Alliander as a contractor. Pallas checked in the organisation if interviews would be possible but that was not the case due to the organisation having other priorities[^2].

[^1]: Vlerick emailbox: 13/12/2023
[^2]: Vlerick emailbox: 8/1/2024

### Rabobank

After explaining my thesis subject to Huib Klamer (ex [VNO-NCW](https://www.vno-ncw.nl/over-vno-ncw/english)), he provided for the contact details of [Eiso Bos](https://www.linkedin.com/in/eisobos/) at the Rabobank. I have contacted Eiso[^3], received a reply[^4] and an introductory call was organised for Friday, February 2nd. I have asked for, and Eiso agreed to facilitate, (a max of) 5 semi-structured 1 hour interviews to take place in the first half of March. I have shared the [introductory presentation](https://eduvlerick-my.sharepoint.com/:b:/g/personal/janru_muller_edu_vlerick_com/ERKTfsg3W1VHv-GLH1fcVJcBqpbvqQIRwqoFu9X1Dooqfw?e=mwBhic) had prepared for the meeting and I also added a [complementary presentation](https://eduvlerick-my.sharepoint.com/:b:/g/personal/janru_muller_edu_vlerick_com/EWeJ1qh9Wx1GtpSYv_chnVEBybZ6sxIXCJbEL15rg9xPHA?e=wCSqAA).[^5]

[^3]: HvA emailbox: 12/12/2023
[^4]: HvA emailbox: 03/01/2024
[^5]: HvA emailbox: 07/02/2024

### Housing Association

No progress has been made on making contact with anybody at a housing association. I did sent an enquiry[^6] to Jim Schuyt (ex [de Alliantie](https://www.de-alliantie.nl/over-de-alliantie/)), but received no response. I will pursue getting in contact with a housing association after finishing the mini case study. It can be of interest to compare a financial service company (private sector) with a semi-public company (such as a utility company or a housing association).

[^6]: gmail emailbox: 22/11/2023

### About the case

From the introductory call it is my understanding that there are approximately 6.000 employees working on compliance related tasks (**check**).

CSRD is outside of Eiso's responsibility. In discussing a possible case two laws to focus on were mentioned.  
- In dutch: de [Sanctiewet (1977)](https://wetten.overheid.nl/jci1.3:c:BWBR0003296&z=2020-05-21&g=2020-05-21)  
- Dutch Anti-Money Laundering and Anti-Terrorist Financing Act (2008), de wet ter voorkoming van witwassen en financieren van terrorisme [wwft (2008)](https://wetten.overheid.nl/jci1.3:c:BWBR0024282&z=2022-11-01&g=2022-11-01)  

Of the two the "Sanctiewet" is shorter, counting 24 articles. The "Sanctiewet" is a framework for implementing various EU sanctions regulations. An example of such sanctions regulations is [Regulation (EU) No. 833/2014](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32014R0833) imposing sanctions on Russia due to the annexation of Crimea.  
The WWFT consists of 107 articles. The WWFT implements various EU directives about Anti-Money Laundering AML. An example of of an EU AML directive is [Directive 2018/843/EU](https://eur-lex.europa.eu/eli/dir/2018/843) (Fifth AMLD). 

Even if the planned interviews are not focussed on CSRD I will still learn the process of translating regulation into systems requirements and ultimately business processes. 

**Comment for AVL and SV:** when speaking to Eiso he seemed not familiar or less familiar with the OCEG model and rather refered to the "three lines of defence model".

On page 4 an initial draft of a proposed interview protocol is included. The goal of the interviews is two fold: 
- First, I would like to use the opportunity to test the familiarity of the subjects with different models that relate to compliance management (and related: risk management). For this I will show 3 existing models. Separately I will ask for feedback on an initial model I have developed that shows (assumed) steps in the process from the creation of regulations until the reporting on compliance with such regulations. 
- Second, I would like to gain an understanding about functions, processes, systems involved in the adoption of new or updated regulations.  

**Question to AVL and SV:** probably stick to one objective at this stage?

### Next steps

If the Rabobank interviews lead to an initial answer of the research question other interviews in the sector can possibly be held. In subsequent interviews the aim would be to link the case to the CSRD guidelines. Large listed companies will for the first time need to report in accordance with the guidelines in 2025, for the 2024 financial year.

There are an approximate 50 NL financial services companies that committed to contributing to the Paris Agreement. The [signatories](https://klimaatcommitment.nl/ondertekenaars/) agreed, among others, to measure CO2 volumes related to their lending and investment. Among this group of companies it shall be possible to research cases specifically in relation to CSRD.

{{< include tables/s2_tbl_fss_organizations.qmd >}}

\newpage

## Initial draft interview protocol

*Before the interview (to be captured in introductory letter/email)*

1. Interview ID:
1. Participant (name & position):
1. Role in the organisation:
1. Professional experience (years):
1. Interviewer:

*General interview data and interview introduction*

1. Date:
1. Start time:
1. End time:
1. Format: individual inperson / individual online
1. Introduce myself and Vlerick
1. Re-explain the subject of the interview
1. Mention expected duration
1. Ask permission to record the conversation

*Questions for checking model familiarity*[^7]  

[^7]: the 4 models mentioned will each consist of a one page diagram and a one page explanatory text.  

1. [Model 1](https://eduvlerick-my.sharepoint.com/:b:/g/personal/janru_muller_edu_vlerick_com/ET8TLbmuOypClT7AiAW0YCIBkhtYw9lYizp9a2Yefleddw?e=cBhcXt) - OCEG Regulatory Change Model (@ocegRegulatoryChangeManagement2018) 
Q1 Are you familiar with the OCEG?    
A1 Yes / No / Somewhat  

1. [Model 2](https://eduvlerick-my.sharepoint.com/:b:/g/personal/janru_muller_edu_vlerick_com/EWXx4Aev5BhEt_3M9tGh_N4BeA2FNm_hkl_FsHuqPHeErg?e=Wsu6tr) - Three Lines of Defence Model (@iiaThreeLinesDefence2020)   
Q2 Are you familiar with the  "three lines of defense model"?  
A2 Yes / No / Somewhat

1. [Model 3](https://eduvlerick-my.sharepoint.com/:b:/g/personal/janru_muller_edu_vlerick_com/EQKtXu29H1hLiJ4oWA1NfaMBjiV1pxttNC6XtkTVT0zvTw?e=60qnQb) - ISO 31000 Risk Management Process (@isoISO3100020182018)  
Q3 Are you familiar with the ISO model?  
A3 Yes / No / Somewhat  

1. Comparing the OCEG model, the ISO model and the Three Lines of Defense Model:  
Q4 Of the three models discussed which is the one you relate to most?  
A4 1 / 2 / 3

1. [Model 4](https://eduvlerick-my.sharepoint.com/:b:/g/personal/janru_muller_edu_vlerick_com/EcFF35AKHRxCmC8MfrDL5EwB71Di1jQE2LCOJORCBuByDQ?e=1SG0xB) Additionally I have drawn a model depicting information flows (down) from regulator to company and reporing flows (up) from company to regulator.  
Q5 Does the diagram approximate the reality in your experience?  
A5 Yes / No / Somewhat

*Questions on Regulatory Change Management* 

Basing yourself on the model you are most familiar with:

1. Were in the organisation are you situated?
1. What are departments/functions you mostly interact with?
1. Which are the main processes that you are involved with?
1. What are the main systems supporting these processes?
1. Are you involved with "translating" regulations into "business rules"?
1. If so, in what way?

Identify & Define

1. Which function is responsible for monitoring EU regulations, decisions and directives?
1. Is the indentification of regulatory risks performed centrally or decentrally?
1. Do you maintain an internal taxonomy related to regulatory risks? 

Track & Analyze

1. Do you have an example of a recent regulatory change?
1. If, for example, there is a change in the EU AML directive: what would specifically happen?
1. How do you find if business processes need to be adapted?

Monitor & Map

1. If business processes need to be adapted, how do you know which ones?
1. What happens in case of conflicting regulations?
1. How are risks mapped to business processes and how is this modelled?

Control & Manage

1. In your organisation how is compliance management embeded? Is it part of a risk management function?
1. If compliance management is under risk management, how are regulatory requirements linked to risks?
1. Is there an individual or a group of individuals responsible for regulatory compliance?

Report & Record

1. How is the audit trail maintained?
1. Can exceptions in an exception report be traced back to regulations?

\newpage

## Previous version: Mini Case Study - Status 28/11/2023

Since the call on 18/10/2023 I have identified 3 prospects where potentially an initial mini case study can be performed with respect to:

RQ-1: What are approaches for aligning business processes with regulatory requirements to achieve regulatory compliance by design?

**MedTech Startup**

[Praxasense](https://praxasense.com/) is a startup developing a heart-rhythm monitorig device. The company is a spin-off of the TU Delft. It was founded in 2019 and it employees 10 people.  
Contact: Leonard Moonen (CEO)  
Address: Molengraaffsingel 12, 2629 JD Delft (NL).

Advantage: the company is small and I would have full access to the team preparing for certification (ISO 13485). ISO 13485 is a norm based on ISO9001 that all companies producing medical equipment need to be compliant with.

Disadvantage: the company is an R&D company that is presently not regulated yet as there are no commercial activities.

**Financial Institution**

[Rabobank](www.rabobank.com) is one of three large banks in the Netherlands. Rabobank exists since 1972. It employs 43 thousand people.  
Contact: Eiso Bos (Global Head Financial Economic Crime Governance, Risk & Change)  
Address: Croeselaan 18, 3521 CB Utrecht (NL)

Advantage: the Rabobank is a well known name (in NL). Performing a mini case study well may lead to doing case studies with other financial institutions.

Disadvantage: I may have limited access to my contact. Also the main processes (of interest to the bank) are likely about KYC (know your customer) and AML (anti money laundering).

**Housing Association**

[Laurentius](https://www.laurentiuswonen.nl/) is a housing association bases in Breda. They rent and maintain some 8.300 real estate objects.  
Possible contact: Paul van Roosmalen (CEO)

Advantage: Two advantages are 1) an advanced data exchange with the government and 2) a possible link with CO2 emissions. Housing Associations are highly regulated in the Netherlands. In September 2022 a covenant has been signed relating to further improve the information exchange with the government (system-to-system) based on SBR (XBRL).

Disadvantage: I have not yet been in contact with a Laurentius, so no visibility about the timeline yet. 

Note: if other cases are situated in the same (housing) sector, further contact is [AEDES](https://aedes.nl/) (vereniging van woningcooperaties).

**Concluding remarks**

Short term most progress can likely be made in a smaller (less complex) organisation?

Longer term the housing association sector can provide for interesting case studies. The information exchange with the government entails more than actual financial data. Next to actual financial data also planning data is exchanged. A sector wide taxonomy has been defined (information model) that facilitates inter-organisation business processes.

\newpage


## Conceptual model - Regulatory Change Management

There is an existing model published by OCEG (&Refinitiv) that is used as a reference. The 2018 version is redrawn below (@RegulatoryChangeManagement2018).

{{< include diagrams/s2_oceg_regulatory_change_process.qmd >}}


# References
