---
title: "Getting the hang of it"
subtitle: "sprint 2"
date: "05-19-2023"
date-format: "DD/MM/YYYY"
date-modified: "05-29-2023"
abstract: ""
format:
  pdf:
    code-fold: True
    latex-clean: True
    include-in-header: 
      text:
        \usepackage{imakeidx}
        \makeindex
        \makeindex[name=authors, title=Authors, intoc=True]
        \makeindex[name=affiliations]
    include-after-body: 
      text:
        \printindex
        \printindex[authors]
jupyter: python3
toc: true
toc-depth: 2
bibliography: "Top100.bib"

---

https://books.google.nl/books?id=r2GmEAAAQBAJ&lpg=PT220&ots=0Pu33IvaV8&dq=xbrl%20dutch%20housing%20association&lr=lang_en&pg=PP1#v=onepage&q&f=false


## [19-05-2023 / s02d01]

Objective for this second sprint:

- Description of finding labels for literature
- Description of Design Science (prof Twente youtube die ook op seminar in Amsterdam was)
- Description of DMAIC method, selectie projecten
- Description of Python Measurement tool
 

Furthermore I want to go back to sprint 1 to "fix things". Specifically, I want to: 

- take out some ideas and put these in a backlog (separate file).
- improve the structure sucht that the sprint is more around the topic "100 papers" (even if I selected only 25)

Already the above seems like a lot for a 14 day sprint. Let's see where we'll get ...

::: {.content-hidden when-format="html"}
This will not appear in a HTML
:::


```{mermaid}
flowchart LR
  A[Hard edge] --> B(Round edge)
  B --> C{Decision}
  C --> D[Result one]
  C --> E[Result two]
```

Use structurizer

| # | Article |  |  | GSReferences | Published in | Journal Score | Principal Author | H-Factor |
|---|---------|--|--|--------------|--------------|---------------|------------------|----------|

{{< pagebreak >}}

## [21-05-2023 / s02d02] Small LLM to ...

semantically query papers in the research database. For example see:

* []()
* Dominik Weckmüller [Semantic Search with Qdrant, Hugging Face, SentenceTransformers and transformers.js](https://geo.rocks/post/qdrant-transformers-js-semantic-search/)


## [20-05-2023 / day02] Authors Index



## [21-05-2023 / day03] Methodology

The paper recommended to my by email (per her email of ): *Design Science in Information Systems Research* [@hevnerDesignScienceInformation2004]. Indeed, in this write-up there are several papers where the Design Science method is applied [@shafagatovaDevelopingToolProcess2021], ... (to be continued).

Exemplars and criteria for applicable design science research (special issue 2018 of the EJIS)

* also check: Christian Sonnenberg

[@cookTechnologyOnlineEducation2014]

## [22-05-2023 / day04] Search strategy

Lets describe the search strategy

* one


## [25-05-2024 / day07] Lean Six Sigma

DMAIC


Voorbeeld
 
* to be excluded in pdf
* to be included in pdf

::: {.panel-tabset}
## R

``` {.r}
fizz_buzz <- function(fbnums = 1:50) {
  output <- dplyr::case_when(
    fbnums %% 15 == 0 ~ "FizzBuzz",
    fbnums %% 3 == 0 ~ "Fizz",
    fbnums %% 5 == 0 ~ "Buzz",
    TRUE ~ as.character(fbnums)
  )
  print(output)
}
```

## Python

``` {.python}
def fizz_buzz(num):
  if num % 15 == 0:
    print("FizzBuzz")
  elif num % 5 == 0:
    print("Buzz")
  elif num % 3 == 0:
    print("Fizz")
  else:
    print(num)
```

:::

## [27-05-2024 / day9] Toepassing voor GeoPandas?

Bestand met locaties van universiteiten?

## [28-05-2023 / day10] Examples of Design Science

Design Science in Information System Research
[@hevnerDesignScienceInformation2004] written by Hevner et al. \index[authors]{Hevner, Alan R. \social[googlescholar]{john.doe}}

Getting Personal: A Deep Learning Artifact for Text-based Measurement of Personality

## [29-05-2023 / day11] Process Modelling

[@mendlingSevenProcessModeling2010] written by 

[@liTextualAnalysisCorporate2010]

[@VICENTESAEZ2018428]

